### PR TITLE
feature(isoslam): Adds functions to extract features from reads

### LINKED ISSUE #88: Extract start, end and length from reads
Currently we have...

``` python
            read1, read2 = pair

            if read1.is_unmapped or read2.is_unmapped:
                continue

            i_total_progress += 1
            i_progress += 1

            if i_progress == 10000:
                # E.debug(str(i_total_progress) + " pairs processed")
                # E.debug(str(i) + "spliced/retained pairs processed")
                i_progress = 0

            read1_start = read1.reference_start
            read1_end = read1.reference_end
            read2_start = read2.reference_start
            read2_end = read2.reference_end
            read1_length = read1.query_length
            read2_length = read2.query_length

```

Where `pair` is derived from fragment iterations of the `bamfile`.

### PR DESCRIPTION
**Pull request by ns-rse**
Closes #88

Adds functions to extract features from a read both individual `pysam.AlignedSegment` and pairs of reads returned from the `pysam.fetch()` iterator.

- Includes tests.
- Extracts
  - `start`
  - `end`
  - `length`
  - tag for `XS` if present, otherwise `None`
  - tag for `XT` if present, otherwise `None`
  - zips up the blocks and returns them as `block_start` and `block_end`

Tests use fixtures defined in `tests/conftest.py` and I had trouble trying to mock `pysam.AlignedSegment` as a number of the attributes I wanted to mock were immutable. I therefore opted to load a `.bam` file and extract some individual `AlignedSegments` as features and use these in the parameterised tests.

However, confusingly the value I used for `start` in the `fetch()` call did not match the first item returned by the generator (this can be seen by the disconnect between the `start` parameters in the `fetch()` calls and the names of the fixtures which reflect the values that are tested and used in the parameter names).

I'm not sure why this is, but one consequence of it is that I'm yet to have extracted any `AlignedSegment` where the `get_tag("XS") == Aligned` and so in turn these are all `None`, similarly there are no `get_tag("XT")` (the transcript id?).

Guidance on how to identify and extract these would be very welcome (I just stuck some `print()` statements into the section of `all_introns_counts_and_info.py` where the `get_tag("XT") calls were made to show the `read1_start` at that point, very crude as I'm still fumbling my way around these files and their specification!).

### CODE REVIEW

**Comment by IanSudbery** [comment]
`fetch` returns any reads that *overlap* with the provided genome region so `fetch(contig="chr1", start=1000, end=2000)` will return an iterator over any reads that overlap with the bases on chromosome 1 bases 1000-2000. 

If we take for example your function:

```
@pytest.fixture()
def aligned_segment_28584(bam_file: AlignmentFile) -> AlignedSegment:
    """Extract an individual AlignedSegment from a ``.bam`` file."""
    return next(bam_file.fetch(contig="chr9", start=28592, end=28593))
```

This will return all reads that overlap chr9:28592-28593. There are 40 such reads. The first one is
```
A00627:697:HFWGNDSX7:4:2549:30553:35869 83      chr9    28585   255     120M1I29M       =       28393   -341    TCAGTTCCACAGTGGGTAACTGTAATTCATTCTAGGTCTGCGATATTTCCTGCCTATCCATTTTGTTAACTCTTCAATGCATTCCACAAATGCCTAAGTATTCTTTAATAATGGTGGTTTGGTTTTTTTTTTTTGCATCTATGAAGTTTT    FFFFFFFFFFFFFFFFFFF:FFFFFFF::FF,FFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  NH:i:1    HI:i:1  NM:i:4  MD:Z:91A25G2T28 AS:i:285
```

I'm guessing that you are looking for a read starting at 28584, given the name of your function. This is indeed this read (pos in the BAM file is 1 based, where as pysam returns 0 based coordinates). 

As for the XS and XT tags - these are added to the bamfile by featureCounts in the pipeline. featureCounts assigns reads to genes/transcripts. The XS tag says whether it is assinged to a gene/transcript or not. XT the transcript to which it is assigned. 

Since the file used here `d0_no4sU_filtered_remapped_sorted.bam` is the input file to the pipeline, it has not yet been run through featureCounts, and so the file doesn't contain the tags.

**Comment by IanSudbery** [comment]
Checking the pysam documentation, it seems you should be able to create the desired AlignedSegment with

```
header_text = "@HD\tVN:1.4\tSO:coordinate\n@SQ\tSN:chr9\tLN:31000\n@PG\tID:STAR\tPN:STAR\tVN:2.7.3a\tCL:STAR   --runMode alignReads   --runThreadN 1   --genomeDir files_for_regression_testing/mini_hg38_genome   --genomeLoad NoSharedMemory   --readFilesIn files_for_regression_testing/d0_no4sU_filtered.1.fq   files_for_regression_testing/d0_no4sU_filtered.2.fq      --outFileNamePrefix files_for_regression_testing/tmp/d0_no4sU_remap   --outStd SAM   --outSAMattributes NH   HI   NM   MD   AS      --outSAMunmapped Within      --outFilterMultimapNmax 20   --outFilterMultimapScoreRange 1   --outFilterScoreMinOverLread 0.33   --outFilterMatchNminOverLread 0.33   --outFilterMismatchNmax 10   --alignIntronMax 500000   --alignMatesGapMax 1000000   --alignSJDBoverhangMin 1   --sjdbOverhang 99   --sjdbScore 2   --twopass1readsN 18446744073709551615   --twopassMode Basic\n@PG\tID:samtools\tPN:samtools\tPP:STAR\tVN:1.12\tCL:samtools view -H d0_no4sU_filtered_remapped_sorted.bam\n@CO\tuser command line: STAR --runMode alignReads --runThreadN 1 --genomeDir
files_for_regression_testing/mini_hg38_genome --outStd SAM --outSAMunmapped Within --outFilterMultimapScoreRange 1 --outFilterMultimapNmax 20 --outFilterMismatchNmax 10 --alignIntronMax 500000 --alignMatesGapMax 1000000 --sjdbScore 2 --alignSJDBoverhangMin 1 --genomeLoad NoSharedMemory --outFilterMatchNminOverLread 0.33 --outFilterScoreMinOverLread 0.33 --twopass1readsN -1 --sjdbOverhang 99 --outSAMattributes NH HI NM MD AS --twopassMode Basic --outFileNamePrefix files_for_regression_testing/tmp/d0_no4sU_remap --readFilesIn files_for_regression_testing/d0_no4sU_filtered.1.fq files_for_regression_testing/d0_no4sU_filtered.2.fq\n"

read_text = "A00627:697:HFWGNDSX7:4:2549:30553:35869 83      chr9    28585   255     120M1I29M       =       28393   -341    TCAGTTCCACAGTGGGTAACTGTAATTCATTCTAGGTCTGCGATATTTCCTGCCTATCCATTTTGTTAACTCTTCAATGCATTCC   ...: ACAAATGCCTAAGTATTCTTTAATAATGGTGGTTTGGTTTTTTTTTTTTGCATCTATGAAGTTTT    FFFFFFFFFFFFFFFFFFF:FFFFFFF::FF,FFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF   ...: FFFFFFFFFFFFFFFFF  NH:i:1    HI:i:1  NM:i:4  MD:Z:91A25G2T28 AS:i:285"

header = pysam.AlignmentHeader(header_text)
read = pysam.AlignedSegment(read_text, header)
```

read_text = pysam.AlignedSegment.fromstring("A00627:697:HFWGNDSX7:4:2549:30553:35869 83      chr9    28585   255     120M1I29M       =       28393   -341    TCAGTTCCACAGTGGGTAACTGTAATTCATTCTAGGTCTGCGATATTTCCTGCCTATCCATTTTGTTAACTCTTCAATGCATTCCACAAATGCCTAAGTATTCTTTAATAATGGTGGTTTGGTTTTTTTTTTTTGCATCTATGAAGTTTT    FFFFFFFFFFFFFFFFFFF:FFFFFFF::FF,FFF:FFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFF:FFFFF:FFFFFFFFFFFFFFFF:FFFFFFFF:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  NH:i:1    HI:i:1  NM:i:4  MD:Z:91A25G2T28 AS:i:285")

**Comment by ns-rse** [comment]
Great, thanks for that @IanSudbery 

I've successfully run these input files through the pre-existing pipeline so should be able to pick up the indexed files as input as whilst manually adding headers is useful I'd like to do this more programatically as I'm setting up tests to work with several different scenarios and using the correct input from the pipeline will be critical to the tests and development.

Unsurprisingly my first attempt this morning failed, but will no doubt have some questions later in the week.

**Comment by ns-rse** [comment]
Ok, I've successfully switched to using the output from the step...

```python
@ruffus.follows(ruffus.mkdir("read_assignments"))
@ruffus.transform(
    name_sort_bams,
    ruffus.regex("name_sorted_bams/(.+).sorted.bam"),
    r"read_assignments/\1/\1.sorted.assigned.bam",
)
def feature_count_read_assignments(infile, outfile):
    """
    Takes `.bam` file and adds 2 tags to it:
        - XT tag tells us the transcript the reads map to
        - XS tag tells us which strand the gene is transcribed from

    NB The `-p` flag is required for SubRead v2.0.6, may need to make this flexible.
    """
    annotation = PARAMS["transcript_gtf"]
    outdir = os.path.dirname(outfile)
    rename_outfile = outfile.replace(".assigned.bam", "")
    statement = (
        "featureCounts "
        "-p "
        f"-a {annotation} "
        f"-o {outdir}/counts.txt "
        "-T 2 "
        "-R BAM"
        f"{infile} &&"
        "mv %(rename_outfile)s.bam.featureCounts.bam %(outfile)s"
    )
    P.run(statement, job_threads=2, job_memory="8G")

```

Two things to note and any thoughts/insights would be appreciated...

## Can not index `.sorted.assigned.bam` file.

I found that the `.bam` files after they have been processed upto this point are not indexable using `samtools index`...

```bash
 ❱ samtools index d0_no4sU_filtered_remapped_sorted.sorted.assigned.bam
[E::hts_idx_push] Unsorted positions on sequence #1: 20490 followed by 15968
[E::sam_index] Read 'A00627:697:HFWGNDSX7:4:1102:12825:32753' with ref_name='chr9', ref_length=31000, flags=99, pos=15968 cannot be indexed
samtools index: failed to create index for "d0_no4sU_filtered_remapped_sorted.sorted.assigned.bam"
❱ samtools index d0_0hr1_filtered_remapped_sorted.sorted.assigned.bam                 
[E::hts_idx_push] Unsorted positions on sequence #1: 23333 followed by 15402
[E::sam_index] Read 'A00627:697:HFWGNDSX7:2:1102:16631:22717' with ref_name='chr9', ref_length=31000, flags=99, pos=15402 cannot be indexed
samtools index: failed to create index for "d0_0hr1_filtered_remapped_sorted.sorted.assigned.bam"
```

In turn this means that `pysam.fetch()` can only be run on the whole file, its not possible to include the options `contig="chr#", start=###, end=###`.

Questions relating to this...

- Is this expected?
- Is it an issue now?
- Could it be an issue in the future if the pipeline were to be modified in the future and require indexing or if only specific regions were to be loaded/targeted in the workflow of `IsoSLAM`?

## Fragment iteration and pairing reads

In `all_introns_counts_and_info.py` there is a function defined [`fragment_iterator()`](https://github.com/sudlab/IsoSLAM/blob/1541287e861f3a01ca61d9bbb497f78d6c6f72a0/isoslam/all_introns_counts_and_info.py#L66).

This pairs up the `AlignedSegment` from each row of a `.bam` file and I've now adapted it to the `extract_segment_pairs()` function in this Pull Request.

In doing so I've written a unittest that checks the number of pairs that are returned and noticed that there are some discrepencies from the number of rows in a given file.

```bash
❱ samtools view d0_no4sU_filtered_remapped_sorted.sorted.assigned.bam | wc -l
1466
❱ samtools view d0_0hr1_filtered_remapped_sorted.sorted.assigned.bam  | wc -l      
3782
```

As you can see in the `tests/test_isoslam.py` the expected number of pairs (derived from the length of the generator that `extract_sgement_pairs()` returns are `710` (for `no4sU` file) and `1845` (for `0hr1` file).

These are _not_ half the number of rows in each file.  I know there is the clause in `extract_segment_pairs()` that checks whether `previous_read == read.query_name` which ensures that rows are not paired with themselves, but it suggests there may be several consecutive rows of `AlignedSegment` in these files with the same `.query_name`.

Questions arising

1. Is it to be expected that there are conseuctive rows with the same `.query_name` in these processed files?
2. Is it reasonable to drop duplicates in this manner?

**Comment by IanSudbery** [comment]
## Indexing

In order to be index, files must be sorted in genome position order, so that the index can encode the offset in the file for each genome region. 

However, the files we are using are name sorted, precisely so that we can group them by read name using the fragment iterator. 

I don't *think* its a problem, as currently I don't think we need random access into the BAM file. `.fetch(until_eof=True)` works without an index, I think, because it just iterates over every read in the file in order. 

## Number of reads in a fragment

There are several reasons why the number of reads in a fragment might not be two. 

Sequencing is "paired end", that means we sequence from either end of each fragment of DNA:

```
------------> Read 1
==========================================================
                                    Read2  <---------------
```

Because the (c)DNA fragment is generated from a particular RNA molecule it is either old or new and one read in the pair showing evidence of being old, means the other read in the pair must also be old. Thus we want to analyse all reads from a fragment together. This is why we group reads into their pairs. 

When we get the reads from the sequencer we need to align them to the genome. While we often refer to the lines in the BAM file as reads, they are actaully alignments of reads to the genome. 

Each read in a pair can have 0, 1 or more alignments to the genome. So you might have read1 aligns, but read2 doesn't, read2 aligns, but read1 doesn't, read1 aligns once, but read2 aligns twice, and so on. Because we are dealing with how often a read doesn't match the reference sequence, it is important for us to be sure the location of the read on the genome isn't ambiguous. Thus, you'll notice that when the generator is consumed, the first thing that happens is a check for whether the length of the alignments associated with the fragment is 2, and if it isn't the fragment is discarded. Thus, I would expect the number of lines coming out of the script to be half the number of input reads or less.

**Comment by ns-rse** [comment]
Thanks for the feedback @IanSudbery 

## Indexing

Good to know that this is expected in light of the ordering undertaken during pre-processing. I just wasn't sure.

Yep, no problems reading the whole file, I'm just trying to anticipate if there would ever be a situation where part of a file were to be read by IsoSLAM. 

I guess if filtering were to be required it could be done in the steps prior to processing with IsoSLAM?

## Number of read fragments

Thanks for the explanation and context. I was expecting the number to be precisely half without that knowledge, it wasn't which threw up a flag so I thought it useful to check.

**Pull request merged**
