### PR TITLE
tests: Ensures regression tests have consistently sorted output

### LINKED ISSUE #67: Tests need constant state
I've noticed whilst working on #65 that the regression test introduced in #62 failed.

As far as I could tell what had changed was the order of entries in the output, which is strange as the current code is looping over things so unless the order of the iterables changes each time code is run I wouldn't expect this to change.

For now though a temporary fix to ensure that the tests always pass is to sort the dataframe that has been introduced to undertake the regression test. This should be done based on the `transcript_id`, `start` and `end` columns.

### PR DESCRIPTION
**Pull request by ns-rse**
Closes #67

Would be useful to have feedback if the proposed sorting for the output is sensible/what is desired.

Also downcase all variable names

### CODE REVIEW

**Review by IanSudbery — COMMENTED** [review]
I think this is fine at the moment. However, I wonder what the performance implications will be when the input is 10Gb, not 50Kb?

**Comment by ns-rse** [comment]
Thanks @IanSudbery 

I appreciate this minimal reproducible example isn't representative of real life. For now though I need a regression test that gives consistent results each time its run so I can refactor the code with confidence that I've not broken anything.

Once I understand the workflow better sorting may be done at another stage and not on a large data frame. It could also be completely configurable as to whether results are sorted so that we enable it during testing and by default disable it in real runs (unless users actually require it). It might be that rather than [Pandas](https://pandas.pydata.org/) dataframes we could use [Polars](https://pola.rs/) which would speed things up if required.

All still very much in the development stage but bringing in a formal testing framework requires output against which comparisons can be made. I've opted to use [`pytest-regtest`](https://pytest-regtest.readthedocs.io/en/latest/) is one approach. I would have liked to give [`syrupy`](https://syrupy-project.github.io/syrupy/) a whirl but Pandas DataFrames aren't yet supported although I've left a note to this effect in the test (see [here](https://github.com/sudlab/IsoSLAM/blob/3fab8c81ff391f90844d55f12b1bc3e5d3b6044b/tests/test_all_introns_counts_and_info.py#L39)) file linking to the relevant GitHub issue that requests support.

**Comment by ns-rse** [comment]
P.S. - Feel free to use the formal GitHub _Review_ and _Approval_ under the _Files changed_ tab, I can override the branch protection rule that requires approval though.

**Comment by IanSudbery** [comment]
Oopps, sorry, I did submit my previous comment via the Review system, but I think I submitted it as a comment, rather than an approval.

**Comment by ns-rse** [comment]
Not a problem :slightly_smiling_face:

**Pull request merged**
